name: Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release Tag
        required: false
      full_test:
        type: choice
        required: true
        description: Execute full test
        default: 'no'
        options:
        - 'no'
        - 'yes'
      upload:
        type: choice
        required: true
        description: Upload artifact
        default: 'no'
        options:
        - 'no'
        - 'yes'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Get modules
      shell: cmd
      run: npm install
    - name: Build
      shell: cmd
      run: npm run build
    - name: Simple test
      shell: cmd
      run: |
        dist\xml2docx.exe demo\demo.docx demo\demo.xml demo\demo.json
        dir demo\demo.docx
    - name: Full test
      if: "${{ github.event.inputs.full_test == 'yes' }}"
      shell: cmd
      run: |
        choco install officeproplus2013
        pip install docx2pdf
        docx2pdf demo\demo.docx
        dir demo\demo.pdf
    - name: Release
      uses: softprops/action-gh-release@v1
      if: "${{ github.event.inputs.tag_name != '' }}"
      with:
        files: dist/xml2docx.exe
        draft: false
        tag_name: ${{ github.event.inputs.tag_name }}
        fail_on_unmatched_files: true
        target_commitish: ${{ env.commit_hash }}
        generate_release_notes: true
    - name: Upload a Build Artifact
      if: "${{ github.event.inputs.upload == 'yes' }}"
      uses: actions/upload-artifact@v3.1.3
      with:
        path: |
          dist/xml2docx.exe
          demo/demo.docx
          demo/demo.pdf
