name: Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release Tag
        required: false
      full_test:
        type: choice
        required: true
        description: Execute full test
        default: 'no'
        options:
        - 'no'
        - 'yes'
      upload:
        type: choice
        required: true
        description: Upload artifact
        default: 'no'
        options:
        - 'no'
        - 'yes'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Get modules
      shell: cmd
      run: npm install
    - name: Build
      shell: cmd
      run: npm run build
    - name: Source code analysis
      shell: cmd
      run: npm run check
    - name: Generate docs
      shell: cmd
      run: npm run docs
    - name: Simple tests
      shell: cmd
      run: |
        npm run test
        npm run test win32
        dir test\\outputs
    - name: Full test
      if: "${{ github.event.inputs.full_test == 'yes' }}"
      shell: bash
      run: |
        choco install officeproplus2013
        pip install docx2pdf
        for i in test/outputs/*.docx; do
          docx2pdf $i
        done
        ls -la test/outputs
    - name: Release
      uses: softprops/action-gh-release@v1
      if: "${{ github.event.inputs.tag_name != '' }}"
      with:
        files: dist/xml2docx.exe
        draft: false
        tag_name: ${{ github.event.inputs.tag_name }}
        fail_on_unmatched_files: true
        target_commitish: ${{ env.commit_hash }}
        generate_release_notes: true
    - name: Upload a Build Artifact
      if: "${{ github.event.inputs.upload == 'yes' }}"
      uses: actions/upload-artifact@v3.1.3
      with:
        path: |
          dist/xml2docx-win.exe
          dist/xml2docx-linux
          dist/xml2docx-macos
          test/outputs
          docs/index.*
