name: Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release Tag
        required: false
      full_test:
        type: choice
        required: true
        description: Execute full test
        default: 'no'
        options:
        - 'no'
        - 'yes'
      upload:
        type: choice
        required: true
        description: Upload artifact
        default: 'no'
        options:
        - 'no'
        - 'yes'
jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Install, build, check and test
      shell: cmd
      run: |
        npm install
        npm run build
        npm run check
        npm run docs
        npm run build-web
        npm run test
        npm run test win32
        dir test\\outputs
    - name: Full test
      if: "${{ github.event.inputs.full_test == 'yes' }}"
      shell: bash
      run: |
        choco install officeproplus2013
        pip install docx2pdf
        for i in test/outputs/*.docx; do
          docx2pdf $i
        done
        ls -la test/outputs
    - name: Prepare release packages
      if: "${{ github.event.inputs.tag_name != '' || github.event.inputs.upload == 'yes' }}"
      run: |
        cd dist
        ren xml2docx-win.exe xml2docx.exe
        7z a -tzip -mx=9 xml2docx-win.zip xml2docx.exe
        ren xml2docx-linux xml2docx
        7z a -tzip -mx=9 xml2docx-linux.zip xml2docx
        del xml2docx
        ren xml2docx-macos xml2docx
        7z a -tzip -mx=9 xml2docx-macos.zip xml2docx
    - name: Release
      uses: softprops/action-gh-release@v1
      if: "${{ github.event.inputs.tag_name != '' }}"
      with:
        files: dist/*.zip
        draft: false
        tag_name: ${{ github.event.inputs.tag_name }}
        fail_on_unmatched_files: true
        target_commitish: ${{ env.commit_hash }}
        generate_release_notes: true
    - name: Upload a Build Artifact
      if: "${{ github.event.inputs.upload == 'yes' }}"
      uses: actions/upload-artifact@v3.1.3
      with:
        name: win32
        path: |
          dist/*.zip
          test/outputs
          web

  build-others:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: darwin
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Install, build, check and test
      run: |
        npm install
        npm run build
        npm run check
        npm run docs
        npm run build-web
        npm run test
        npm run test ${{ matrix.platform }}
        ls -la test/outputs
    - name: Upload a Build Artifact
      if: "${{ github.event.inputs.upload == 'yes' }}"
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ${{ matrix.platform }}
        path: test/outputs
