name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Get modules
      shell: cmd
      run: npm install
    - name: Build
      shell: cmd
      run: npm run build
    - name: Simple test
      shell: cmd
      run: |
        dist\xml2docx.exe demo\demo.docx demo\demo.xml demo\demo.json
        dir demo\demo.docx
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: dist/xml2docx.exe
